### ISSUE TITLE
Problems running Poshnmap with the new version of nmap

### ISSUE THREAD

**Issue by fjvasquez** [JustinGrote/PoshNmap#13] opened 2021-11-03 23:05 UTC
When I try to run the command invoke-nmap www.google.com there is an error about Sytem.object not being able to be converted to xml objects.

**Comment by JustinGrote** [comment] 2021-11-03 23:45
Hi, can you tell me which version of PS and nmap you are on?

**Comment by fjvasquez** [comment] 2021-11-03 23:51
Powershell: 7.1.5
Nmap: 7.92

**Comment by JustinGrote** [comment] 2021-11-03 23:59
I'll give it a review when I get a chance.

**Comment by fjvasquez** [comment] 2021-11-04 00:19
Thanks.

**Comment by JustinGrote** [comment] 2021-11-04 15:57
I can reproduce, I didn't have the latest installed. Looks like they changed the XML format
![image](https://user-images.githubusercontent.com/15258962/140375599-afaa6351-cbcd-415c-abf6-76bb464b71a3.png)

**Comment by JustinGrote** [comment] 2021-11-09 00:38
@fjvasquez this should be fixed in 0.6.1, I'm closing, please comment here if it still doesn't work for you.

**Closed as completed by JustinGrote** 2021-11-09 00:38 UTC
